In [1]:
import pandas as pd
import numpy as np

In [2]:
df: pd.DataFrame = pd.read_csv("btc_usd_data.csv")
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2019-11-08 00:00:00+00:00,9265.368164,9272.759766,8775.534180,8804.880859,24333037836,0.0,0.0
1,2019-11-09 00:00:00+00:00,8809.468750,8891.818359,8793.163086,8813.582031,17578630606,0.0,0.0
2,2019-11-10 00:00:00+00:00,8812.489258,9103.826172,8806.162109,9055.526367,20587919881,0.0,0.0
3,2019-11-11 00:00:00+00:00,9056.917969,9081.279297,8700.608398,8757.788086,20265510765,0.0,0.0
4,2019-11-12 00:00:00+00:00,8759.751953,8853.768555,8685.427734,8815.662109,20309769107,0.0,0.0
...,...,...,...,...,...,...,...,...
1823,2024-11-04 00:00:00+00:00,68742.132812,69433.179688,66803.648438,67811.507812,41184819348,0.0,0.0
1824,2024-11-05 00:00:00+00:00,67811.171875,70522.789062,67458.867188,69359.562500,46046889204,0.0,0.0
1825,2024-11-06 00:00:00+00:00,69358.500000,76460.156250,69322.031250,75639.078125,118592653963,0.0,0.0
1826,2024-11-07 00:00:00+00:00,75637.085938,76943.117188,74480.421875,75904.859375,63467654989,0.0,0.0
1827,2024-11-08 00:00:00+00:00,75900.031250,76516.070312,75690.789062,76360.164062,60405792768,0.0,0.0

In [3]:
df.drop(["Dividends", "Stock Splits", "Date"], inplace=True, axis=1)
df

              Open          High           Low         Close        Volume
0      9265.368164   9272.759766   8775.534180   8804.880859   24333037836
1      8809.468750   8891.818359   8793.163086   8813.582031   17578630606
2      8812.489258   9103.826172   8806.162109   9055.526367   20587919881
3      9056.917969   9081.279297   8700.608398   8757.788086   20265510765
4      8759.751953   8853.768555   8685.427734   8815.662109   20309769107
...            ...           ...           ...           ...           ...
1823  68742.132812  69433.179688  66803.648438  67811.507812   41184819348
1824  67811.171875  70522.789062  67458.867188  69359.562500   46046889204
1825  69358.500000  76460.156250  69322.031250  75639.078125  118592653963
1826  75637.085938  76943.117188  74480.421875  75904.859375   63467654989
1827  75900.031250  76516.070312  75690.789062  76360.164062   60405792768

[1828 rows x 5 columns]

In [19]:
sliding_window_size: int = 3

In [20]:
print(len(df))

1828

In [24]:
X: list[list[int]] = []
Y: list[int] = []
for num in range(0, len(df) - sliding_window_size - 1):
    X.append([])
    for row in df[num:(num+sliding_window_size)].itertuples():
        X[num].append(row.Open)
        X[num].append(row.Close)
        X[num].append(row.High)
        X[num].append(row.Low)
        X[num].append(row.Volume)
        Y.append(df["Close"][num+sliding_window_size+1])

print(X[0])
print(Y[0])

[9265.3681640625, 8804.880859375, 9272.759765625, 8775.5341796875, 24333037836, 8809.46875, 8813.58203125, 8891.818359375, 8793.1630859375, 17578630606, 8812.4892578125, 9055.5263671875, 9103.826171875, 8806.162109375, 20587919881]
8815.662109375